statements = [expr, { NEWLINE, expr }];
expr = var_expr | term, { (PLLUS | MINUS), term };
var_expr = "var", IDENTIFIER, "=", expr;
term = factor, { (MULTIPLY | DIVIDE | MOD), factor };
factor = brace_expr | INT | FLOAT | IDENTIFIER;
brace_expr = "(", expr, ")";